### ISSUE TITLE
Please provide TorrentAddFile with payload options.

### ISSUE THREAD

**Issue by shric** [hekmon/transmissionrpc#11]
Note: I'm happy to attempt the PR if you let me know which strategy you'd prefer, please let me know.

I'd like to either export `file2base64` or provide another function which takes a filename and a `TorrentAddPayload`.

Let's say I want to add a torrent in a paused state. I can easily do this with a URL:
```
url := "http://..."
paused := true
payload := &transmissionrpc.TorrentAddPayload{
  Filename: &url,
  Paused: &paused,
}
torrent, err = client.TorrentAdd(payload)
```
If I want to add a file, there's the wrapper:
```
filename := "foo.torrent"
client.TorrentAddFile(filename)
```
But if I want to add that file paused, I need to reinvent `TorrentAddFile`, which is painful as `file2base64` is not exported.

**Comment by hekmon** [comment]
I see...

Would exporting file2base64 be enough in your case ? If so, I would be glad to review a PR :)

(don't forget to update/add your case in the readme !)

**Comment by hekmon** [comment]
I published a new minor release containing your contribution: [v1.1.0](https://github.com/hekmon/transmissionrpc/releases/tag/v1.1.0)

Thanks again :)

**Comment by shric** [comment]
Hey, thanks very much for accepting, it was an easy PR!
