### ISSUE TITLE
go get doesn't install v2

### ISSUE THREAD

**Issue by ay18** [hekmon/transmissionrpc#17]
When running `go get github.com/hekmon/transmissionrpc/v2`, the follow message is returned.

go get: module github.com/hekmon/transmissionrpc@upgrade found (v1.1.0), but does not contain package github.com/hekmon/transmissionrpc/v2

**Comment by hekmon** [comment]
Thank you for the report !

Indeed the go module was left behind (tagging alone does not work). Should be fixed with [v2.0.1](https://github.com/hekmon/transmissionrpc/releases/tag/v2.0.1), let me know if this is not the case.
