### ISSUE TITLE
Why is MarshalJSON needed for torrent_mutators.go instead of using omitempty?

### ISSUE THREAD

**Issue by hyperreal64** [hekmon/transmissionrpc#20]
Hello,

I'm currently working on making this library compliant with Transmission RPC spec v17. I'm wondering what the reason is behind the MarshalJSON function for TorrentSetPayload instead of using `omitempty`. I'm sure there is a valid reason, I'm just trying to understand the code better.

Thanks for making this! Also: I noticed in the other issue, you mentioned you don't have time to maintain this. I would gladly take over maintainership if that is fine with you. I have forked this repo but I've had to change the Go modules to my repo in order to test my changes. This seems like it would conflict with making a pull request since both repos would be using different module URLs. I'm fairly new to this and I've never made PRs for Go projects before, so maybe there is a way to workaround this. Or else if you'd like to archive this repo and we can just use mine as the new one. I'm open to discussion about this.

Best regards

**Comment by hekmon** [comment]
In case you do want to send a default value as a valid mutator value. For exemple if you use omit empty but you want in a case to the send `0` as a valid value... you can't.

So the only way to respect this + "the payload must only contains actual actions to be performed". You have to differentiate "none" from default value (which is used by omitempty).

To be honest I have not given up on this lib, I am just not able to [work on it actually](https://github.com/hekmon/transmissionrpc/issues/19#issuecomment-1473760663). For now, I think the best way is to work thru PR and having multiple people validating the proposed changes (by testing them as I won't be able to) and publish new versions. Heads for #19 for more on this.
