### ISSUE TITLE
FR: Expose http.Client.

### ISSUE THREAD

**Issue by davidnewhall** [hekmon/transmissionrpc#23]
If you're considering dropping a v3 tag after we figure out the RPC version changes...

I'd like to suggest a few things. 
1. Instead of taking in a bool for `https` and a string for `uri`, can we consider just providing a full url? Then the implementer can decide how their users input data, and split or join it themselves. This removes the need to join all the pieces in this library and run `url.Parse`. 
2. Instead of a `time.Duration` for HTTPTimeout, can we just take in an `http.Client`? This also removes the need for a dependency on hashicorp's cleanhttp module. You can let the implementer pass in their own client with a timeout pre-applied. The reason I want this is so I can log payloads and produce metrics with `http.Transport` middleware.
- I may run into more suggestions as I add code to use this library, but these were the first problems I ran into. I have similar integrations for deluge, qbit, nzbget, rtorrent, and all 5 Starr apps; they all use a custom http.Client.

I'm happy to drop in a pull request if you're open to these changes.

**Comment by hekmon** [comment]
This lib was one of my first Golang project back then and I would definitely implements init differently if I was to restart it now.

1. Absolutely, way more KISS
2. Even I do not like libs that do not let me specify a custom http.Client now (for tracing purpose mostly) so yeah that is something I would agree on

And your are right, changing major semver is the right opportunity to do so.

I hope to have a little bit more time during July. Do not hesitate to do PR, we can focus the discussion on changes there. I won't release a new tagged version until I am sure to have time to test everything, but in the mean time we can get the PR merged in order for you to target a specific commit on master and keep this going forward.

I am a bit sad that no one validated the work of @hyperreal64 in #21, this would have been merge on master by now with just a bit of feedback from people from the #19...

**Comment by davidnewhall** [comment]
I can test 21 if we can get the http.Client change merged into it. At least I can test it a little bit. My intention is to pull pretty basic data about files being transferred or seeding. I have at least 2 users that will use it, and more in time. I'll admit I am totally unfamiliar with transmission's API, and I probably won't write enough code to become as familiar with it as you. I'll do what I can though.

**Comment by davidnewhall** [comment]
I also implore you to bump the go version in the repo go.mod file to 1.18 or 1.19.

**Comment by davidnewhall** [comment]
> I hope to have a little bit more time during July.

I'm ready to cut a new release of my app, but I need a new release of your module. Can you return for an hour to merge things in? I think we're all good now. If you're not going to have time, you're welcome to add me as a contributor on this repo and I'll maintain it until you have time. Otherwise, please let me know you don't have time and I'll fork this repo to golift.io and maintain it there. Thanks!

**Comment by davidnewhall** [comment]
yaaaaaaaa buddy! And congrats on the new kid. :)
