### ISSUE TITLE
Allow to request and edit torrent information via hashes

### ISSUE THREAD

**Issue by elboletaire** [hekmon/transmissionrpc#4]
Based on the transmission-rpc documentation, ids arrays can be as follows:

       All torrents are used if the "ids" argument is omitted.
          "ids" should be one of the following:
          (1) an integer referring to a torrent id
          (2) a list of torrent id numbers, sha1 hash strings, or both
          (3) a string, "recently-active", for recently-active torrents

I've been trying out, and I may be missing something (or messing with something, I'm kinda newbie with golang), but I think your library does not support option 2, right?

It would be really nice to allow searching via hashes, many applications do not return the numeric id and, instead, use the string hash (like sonarr).

**Comment by hekmon** [comment]
Is not https://github.com/hekmon/transmissionrpc#torrent-action-requests what your are looking for ? :)

For example:
https://godoc.org/github.com/hekmon/transmissionrpc#Client.TorrentReannounceHashes

**Comment by elboletaire** [comment]
I've seen those, but there is no `TorrentGetAllForHashes`, which is what I'm asking. Unless there's a method I missed, the ones for getting the torrents can only be filtered using `[]int64`.

**Comment by elboletaire** [comment]
I expose my use case, so you can understand why I want this:

- I use sonarr to automatically download torrents.
- Once downloaded, sonarr gives me the hash ID (only hash ID, no int64 value).
- I don't like how sonarr renames Anime and other stuff, so I'm creating it on my own; hence, I'd use `TorrentRenamePath`, which payload is:

```go
type TorrentRenamePathPayload struct {
	IDs  []int64 `json:"ids"`  // the torrent torrent list, as described in 3.1 (must only be 1 torrent)
	Path string  `json:"path"` // the path to the file or folder that will be renamed
	Name string  `json:"name"` // the file or folder's new name
}
```

As I've previously seen it asks for `[]int64` I was trying to find out which ID my torrent has, based on its hash, but then I realized that most of the methods only accept `[]int64`, so I can't find a way to get it from its hash.

BTW, if the `TorrentRenamePathPayload` accepts a hash (as it's specified in the transmission rpc specification) I wouldn't need to first ask for the ID, and then use the hash.

So my feature request/question is, couldn't it be set as `[]interface{}` instead, so it allows other type of arrays and not only arrays of ints? (please, remember I'm a newbie.. so correct me if I'm wrong and that can't be done)

**Comment by hekmon** [comment]
Yes because the RPC documentation does mention "a list of torrent id numbers, sha1 hash strings, or both" but only for [Torrent Action Requests](https://github.com/transmission/transmission/blob/2.9x/extras/rpc-spec.txt#L86) (`torrent-start`, `torrent-start-now`, `torrent-stop`, `torrent-verify`, `torrent-reannounce`) but not for [Torrent Accessors](https://github.com/transmission/transmission/blob/2.9x/extras/rpc-spec.txt#L142) (`torrent-get`).

About `TorrentRenamePathPayload` I can't see where in the [documentation](https://github.com/transmission/transmission/blob/2.9x/extras/rpc-spec.txt#L438) it can accept a hash, only 1 ID (within an array don't ask me why). Could you link me the line where you saw it ?

I'm not familiar with Sonarr (I use my own bots for watching/dwld) and there is something I don't quite understand: does sonarr start the downloading directly within transmission ? or does it download the torrent file/magnet that you then need to feed to transmission ? (watch directory or API)

**Comment by elboletaire** [comment]
In the documentation,  under the Renaming a Torrent's Path section, says:

     "ids"      | array      the torrent torrent list, as described in 3.1 | (must only be 1 torrent)

The section 3.1 is the first one I pasted in this issue, so I understand it should accept hashes. It says it has to be one torrent, but if it points to the section 3.1, I understand it should work.

Anyway, I'm gonna try it right now using a REST client, just to ensure I'm really understanding it well.

> I'm not familiar with Sonarr (I use my own bots for watching/dwld) and there is something I don't quite understand: does sonarr start the downloading directly within transmission ? or does it download the torrent file/magnet that you then need to feed to transmission ? (watch directory or API)

Sonarr uses the torrent API for downloading and tracking torrernt files, but the script I'm doing is called after, directly by sonar, nothing related to Transmission, and that call [only has some environment vars](https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts), which do not include the numeric torrent id.

**Comment by elboletaire** [comment]
I can confirm it allows hashes as IDs:

![imatge](https://user-images.githubusercontent.com/153305/58329689-6edf3880-7e35-11e9-9e26-1067c020a20f.png)
![imatge](https://user-images.githubusercontent.com/153305/58329716-7dc5eb00-7e35-11e9-8ca0-e3ed1a274e01.png)

**Comment by hekmon** [comment]
I guess it could, I never try it my self. I would be glad if you send a PR with support for such use case if your test succeed :)

For your initial request you could have have an intermediate helper function:
```go
func GetIDFromHash(hash string) (id int64, err error) {
    // Get all torrents with hash & id
    torrents, err := client.TorrentGet([]string{"hashString", "id"}, nil)
    if err != nil {
        err = fmt.Errorf("can't get the torrents list: %v")
        return
    }
    // Search loop
    for _, torrent := range torrents {
        if torrent.HashString == hash {
            id = torrent.ID
            return
        }
    }
    err = fmt.Errorf("hash '%s' can't be found with torrents list", err)
    return
}
```

**Comment by elboletaire** [comment]
Yeah but you're requesting all the torrents and then looping them... I'd prefer not asking more than what I need to the transmission server (my actual transmission server has more than 300 downloads active, it's not a good idea to query it with all the torrents every time I need to rename just one).

Ok I'll see if I can do such changes on my own :)

**Comment by hekmon** [comment]
Great news ! (for your tests)

About the function, even if you are requesting all torrents, daemon only yields `ID` and `HashString` not all the metadata about every torrents, which compensate a bit having to use an intermediate call even on several hundreds torrents.

I won't have any free time this week end, so I might only start implementing this next weekend or so. In the mean time, if you feel ready to add on your own:

* `TorrentGetHashes(fields []string, hashes []string)`
* `TorrentGetAllForHashes(hashes []string)`
* `TorrentRenamePathHash(hash string)`

I would be glad to accept your PR :)

**Comment by hekmon** [comment]
Can you confirm the adjustments made in https://github.com/hekmon/transmissionrpc/commit/5acf25e958e61b33ecd31b27d51ad5d30fef3c67 are working for you ? I will then close this issue.

**Comment by elboletaire** [comment]
Yup, they work pretty well.

**Comment by hekmon** [comment]
Great !

Thank you again for your PR :+1:
