### ISSUE TITLE
Tiny inconsistency with field names - Peerlimit and PeerLimit

### ISSUE THREAD

**Issue by tanelpuhu** [hekmon/transmissionrpc#8]
While the `TorrentSetPayload` is using `Peerlimit`, `Torrent` and `TorrentAddPayload` are using `PeerLimit`.

```$ ack -w Peerlimit
torrent_mutators.go
44:	Peerlimit *int64 `json:"peer-limit"` // maximum number of peers


$ ack -w PeerLimit
torrent_add.go
76:	PeerLimit *int64 `json:"peer-limit"` // maximum number of peers

torrent_accessors.go
157:	PeerLimit *int64 `json:"peer-limit"`
```

Just stumbled on it when trying to dynamically compare `Torrent` field values with configuration I have and dynamically (again😄, basically like `MarshalJSON` does here also) generating TorrentSetPayload if there are differences.

I could make also PR if this change is ok but might break functionality for other using this?

**Comment by hekmon** [comment]
Damn... I had to reread several times to spot it 😅

I will be glad to take ur PR ! This is definitely a breaking change but... Project is still WIP as indicated on README (no formal v1.0.0 version yet).

I think after your PR, I'm gonna start version from v0.1.0 to ease dependency management for other projets but still allow me breaking changes until at least all RPC calls are implemented 😃

**Comment by tanelpuhu** [comment]
Yeah, I could have been more clear about it :smiley:

**Comment by hekmon** [comment]
Fixed by https://github.com/hekmon/transmissionrpc/pull/9
